### ISSUE TITLE
Create Form Page - TODO and Improvement

### ISSUE THREAD

**Issue by phamthanhhang208** [phamthanhhang208/survey-app#6]
**TODO** 
- [x] Add validator to question type
- [x] Add drag and drop to change question order

**IMPROVEMENT**
- [x] question text should be text area and can span multiple lines (enable autosize)
- [x] Add required marks to questions that required
- [x] Should have a preview link 
- [x]  BackTop to go back to the top of the page

**Comment by phamthanhhang208** [comment]
- [x] In checkboxes and multiple-choice, all answers must have unique value
